### ISSUE TITLE
How to configure this ext so that it works?

### ISSUE THREAD

**Issue by rowild** [macieklad/tailwind-sass-syntax#1]
First of all: thanks for your extension!

I am trying it out, but unfortunately it does not work. Things like `@tail` or `@apply` are still not recognized. 

Is there anything special in the setup of VSCode that has to be configured or turned off in order to make your ext work?

**Comment by macieklad** [comment]
The plugin adds syntax based on file extension, it should work out of the box. I've tested the extension not so long ago, but maybe with the incoming 1.0.0 of tailwind new things may got in our way.

Could you give me a way to reproduce the issue, for example the file you are working on ? I will take a look on the extension today when I will have the time, so for now, we could do this much :) 

Thank you for the report !

**Comment by rowild** [comment]
That might be it: I am using v1, not 0.7.4. 
My setup is conventional: A simple tailwind.css file that uses the standard imports. I will test with tailwind .7.4 and report back (but in a couple of days only, since I need to finish my project...)

Thanks for your quick feedback!

**Comment by klocus** [comment]
Cześć, Maciej ( ͡° ͜ʖ ͡°)

I've got the same problem with 0.7.4 version of Tailwind. Should I change something on default VSC settings? I use SCSS.

**Comment by macieklad** [comment]
I tested the ext once more, and everything seems to play just fine, in multiple projects. There is no need to change anything in vscode, as the extension only adds new grammar to the existing sass highlighting, so as soon as vscode recognizes sass or scss code, it should work. Could you provide a situation (for example part of the file, or setup you're working with) where it does not work for you ? Maybe I'm missing some key point.

**Comment by klocus** [comment]
So I'm using "project from folder" (I've also tried workspace). I'm also using Laravel Mix:

```js
let mix = require('laravel-mix');
var tailwindcss = require('tailwindcss');

mix.js('src/js/app.js', 'assets/js/');
mix.sass('src/scss/style.scss', 'assets/css/')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.js') ],
    });

mix.browserSync({
    proxy: 'domain.test'
});
```

You can see my path to SCSS. In `src/scss/style.scss` I use ` @import "components/buttons";`.

Here is a sample of my code:

![Sample](https://i2.yapics.com/04/04/230420Ye04.png)

Folders structure: https://snag.gy/vPu0y4.jpg

PS. I'm runnig VSC on Mac (High Sierra).

**Comment by macieklad** [comment]
May I ask, is that pink/purple highlight of apply rule the same as for example @media rules ? If yes, the plugin works correctly, as it only adds syntax highlighting as the name suggests. What causes problems then is the sass linter itself, as these custom rules are not a part of the language. 

The simple solution is to add an ignore for them, for example in the .stylelintrc file if you use one, or the global linter config.  I may consider adding such feature in the future, but I don't think there is sense right now, as it can be done easily right now with a line or two of config.

Please drop me a line if it worked for you 😉

**Comment by klocus** [comment]
@macieklad Yup, you have right! Sorry for that :)

Btw. Do you have any idea for disable checking "}" by the lint at Taildwind's properties?

**Comment by macieklad** [comment]
Under user or workspace settings you can add: 
`
{
 "scss.validate": false
}
`
It will turn off scss validation for unknown tags

**Comment by kylecordes** [comment]
I encountered the same difficulty, and worked around it with the same setting. I had assumed that the purpose of this extension included making the Sass support understand that (among other things) the presence of an "apply" directive meant a rule is valid and not empty. But that appears to not be the case; this extension only makes VSCode understand how to syntax highlight the directive. You can separately turn off aspects of the Sass support already in VSCode, there is not yet (as far as I know) anyway to fully support tailwind+Sass syntax and semantics.
