### ISSUE TITLE
Highlight classes that are @applied

### ISSUE THREAD

**Issue by filipesmedeiros** [macieklad/tailwind-sass-syntax#10]
Can we color the classes that come after the `@apply`? Maybe with the same color that they have on the rest of the code?

Thanks! Nice extension

**Comment by macieklad** [comment]
Sorry for not responding for over a month. I had this on my radar, I was thinking whether it won't look weird, but at the end I must say the effect seems quite nice. So with version 1.2 (already published), this feature is included. We shall see how others will react to this change, and whether it will stay. Thank you for your feedback!
